baseurl = "/"
languageCode = "en-us"
title = "Jahon Amir"
theme = "hugo-theme-massively"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Profile"
    url = "/profile/"
    pre = "<i class='now-ui-icons users_single-02'></i>"
    weight = 2

[[menu.footer]]
    identifier = "linkedin"
    pre = "<i class='fa fa-linkedin'></i>"
    url = "https://linkedin.com/in/jahonamir"
    weight = 1
[[menu.footer]]
    identifier = "github"
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/jahonamir"
    weight = 2
[[menu.footer]]
    identifier = "copyright"
    name = " Jahon Amir - Developed Using R Blogdown, Hugo, and Now UI"
    pre = "<i class='fa fa-balance-scale'></i>"
    url = "https://spdx.org/licenses/MIT"
    weight = 3


[params]
    background = "/img/bg11.jpg"
    tint = "black"
    custom_css = ["css/highlight.min.css"]
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "Jahon Amir"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"


