languageCode = "en-us"
title = "Jahon Amir"
baseURL = "/"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

        
# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"

# Below parameters can be set to override default post settings
[params.posts]
    folderName = "post"
    pageSize = "12"
    featuredPost = false
    paginationPages = 1
    showFirstLast = false
    disableComments = true
 
#[languages]
#[languages.en]
#  languageName = "English"
#[languages.es]
#  languageName = "Español"
#  title = "Massively - Versión Español"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"
