---
title: "Experience"
author: "Jahon Amirebrahimi"
date: 2017-01-01
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

Energy analyst, UC Berkeley MPP, and UC Davis MS Candidate with a background in energy finance, markets, greenhouse gas, and policy modeling and analysis.  Experience includes:  
  
*  Project finance and life-cycle greenhouse gas modeling   
* Cleantech and energy market and policy analysis   
* Strategy development for entering emerging markets and governance  
* Corporate, academic, and government policy writing and publishing  
* Developing and maintaining relationships with external stakeholders, including goverments, advocacy groups, and contractors.    
* Managing high-budget energy infrastructure programs ($3.5M+) in fast-paced, cross-functional, multi-stakeholder environments
  
## Lawrence Berkeley National Laboratory
Energy Technologies Area: Electricity Markets and Policy Group, Sustainable Energy Systems Group  
**Bioenergy Researcher**  
Aug 2017 - Aug 2019  
  
Researched with two groups to model future bioenergy project finance, market, and greenhouse gas impacts in California.  
    
* Expanded California dry anaerobic digestion facility economic and life-cycle emissions model integrating new operational data, emission impact vectors, and several scenarios highlighting alternate facility configurations and state markets.  
* Developed bioenergy by-product utilization model characterizing end of life resource, economic, and greenhouse gas implications through to 2150 per county in California.  
* Published in Environmental Science and Technology  
* Programmed in R  
  
## Opcondys
Haas Cleantech to Market Program  
**Business Analyst**  
Aug 2018 - Dec 2018  

Determined value proposition and market strategy for an emerging high voltage power electronic technology and company.  

## Strategen
California Energy Storage Alliance  
**Energy Analyst**  
Jan 2018 - May 2018    
  
Evaluated the market impacts of Community Choice Aggregators for energy storage stakeholders and developed strategic plan.  

## California Public Utilities Commission
Administrative Law Judge Division  
**Regulatory Analyst**  
Jan 2018 - May 2018  
  
Audited investor owned utility marketing, education and outreach program and energy efficiency.  

## California Environmental Protection Agency
CalRecycle, Executive Policy Office  
**Policy Analyst**  
Jan 2016 - Jan 2017  
  
Worked with executive policy team to advance emerging climate and bioenergy legislation through stakeholder relations, regulation development, and policy analysis.

* Led local government policy analysis regarding bioenergy and secondary market feedstock quality. 
* Drafted public-facing budget change proposal and policy recommendations to shape public discourse around SB 1383 and SB 168.  

## City of Kalgoorlie-Boulder
Department of Sustainability  
**Energy Project Manager**  
Aug 2015 - Jan 2016  
  
Managed and executed federally funded multi-million dollar renewable energy projects for regional West Australia.

* Contracted project feasibility reports for solar, wind, and LED streetlight installations.  
* Allocated and managed $3.5 million in federal grant funding.  
* Lobbied and passed city-wide resolution for 125 kW solar rooftop installation.  
* Drafted and negotiated demand-side management contract.
* Supervised LED streetlight project roll out and authorized purchase orders.  
* Maintained 300kW solar and 100kW geothermal capacity facilities.  
* Periodically reported to government stakeholders and contractors.  